# What program(s) have to be built
PROGRAMS = ex5

# Dependencies for the program(s) to build
ex5: ../common/utils.o ../common/remregs.o ../common/wperror.o ../common/robot.o ex5.o

# Includes the common Makefile with the various rules
include ../common/Makefile.inc